project:
  type: website
  output-dir: docs

website:
  title: "cours"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Accueil.qmd
      - mes_cours.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



